### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by odvigajlo** [niels747/Weather_Sim_4#2]
Dust: it would be cool if niels will add sand and if wind will blow over it than dust will create. So we can make duststorms!
Biomes: Different biomes would be cool too! Like savanna desert and other.
Addition To Biomes Idea: Maybe biomes can eventually occur in map. Like in dry warm places deserts, and in humid warm rainforests

**Comment by niels747** [comment]
I will add the duststorms and I will enhace the surface moisture/vegetation. There won't be clear biomes, but a smooth range of surfaces: from completely dry and barren like a desert, to very wet with lots of green like a rainforrest.
The dust and forrest fires will be affected by this

**Comment by niels747** [comment]
Please add any further suggestions to the "Weather Simulation Suggestions" thread
