### ISSUE TITLE
Super Slow Now

### ISSUE THREAD

**Issue by adamorgler** [niels747/Weather_Sim_4#3]
I used to be able to run this at about 30-60fps but now I'm lucky if I get above 5fps. Anyone else having this issue too?

**Comment by adamorgler** [comment]
I figured it out. I apparently turned off "Use hardware acceleration when available" in my browser's settings.

**Comment by niels747** [comment]
> I figured it out. I apparently turned off "Use hardware acceleration when available" in my browser's settings.

I'm glad you figured it out by yourself. Without Hardware acceleration your poor cpu will have to run all the shader code. Even if you have a very fast cpu with many cores it can never come close to the processing power of a modern GPU
