### ISSUE TITLE
Droplet bugg!

### ISSUE THREAD

**Issue by panagiotisLadis1235** [niels747/Weather_Sim_4#7]
problem with rain/snow when it touches the ground creates clouds that fill the map also does not create grass or snow.

**Comment by niels747** [comment]
I changed something, please tell me if this fixed it. I can't reproduce your issue so you have to tell me.

**Comment by panagiotisLadis1235** [comment]
No is stop loading 86%

**Comment by panagiotisLadis1235** [comment]
precipitation shader.frag

**Comment by niels747** [comment]
precipitationShader.frag wasn't changed, so it can't be the problem.
wat is the error in the console?

**Comment by panagiotisLadis1235** [comment]
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()
forestFire.png:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by panagiotisLadis1235** [comment]
Is fixed thx!!
